source 'https://rubygems.org'

gem 'selenium-webdriver','2.46.2'
gem 'commonwatir'
gem 'watir'
gem 'minitest'
gem 'cucumber'
gem 'watir-webdriver'
gem 'rspec'
gem 'headless'
gem 'rspec-expectations'
gem 'test-unit'